name: Tox tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12"]

    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py

  test-py36:
    runs-on: ubuntu-latest
    container: python:3.6-slim

    steps:
      - uses: actions/checkout@v6
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py
